# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . /app/

# Install the MCP server package
RUN pip install --no-cache-dir .

# Default environment settings (can override via config)
ENV OLLAMA_HOST="http://localhost:11434"
ENV OLLAMA_LOG_LEVEL="INFO"
ENV OLLAMA_ENABLE_CACHE="true"

# Run as a stdio MCP server
CMD ["python", "-m", "ollama_mcp_server.main"]
