# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Copy project files
COPY pyproject.toml poetry.lock* /app/
COPY requirements.txt /app/
COPY . /app

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    pip install --no-cache-dir . && \
    apt-get remove -y build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Default command
CMD ["python", "-m", "ollama_mcp_server.main"]
